#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// gen-tokens.mjs — canon → code token codegen (the canon-resolver, step 1).
//
// Reads a brand's canon masters and emits typed, importable token files so
// engine code can stop hardcoding design values (AM_FIELDS, style.css :root):
//
//   Sources (never re-typed here):
//     <brandRoot>/canon/americana-tokens.json  — canon SSOT (field bgs, accents)
//     <brandRoot>/canon/tokens-pending.json    — values that exist ONLY in code
//                                                today (field fg/muted/hairline,
//                                                solid signal bg, css :root vars);
//                                                each must migrate into the canon
//                                                file and then leave pending.
//
//   Outputs (into <brandRoot>/src/generated/, or --out <dir>):
//     tokens.ts        — typed constants: FIELDS (=== Video.tsx AM_FIELDS values),
//                        ACCENTS, CSS_VARS
//     tokens.css       — the :root custom-properties block (=== style.css :root)
//     token-names.ts   — string-literal unions (FieldName, AccentName, CssVarName)
//     token-names.json — same data for .mjs scripts
//
// Deterministic + idempotent: output order follows source JSON key order; the
// same inputs always produce byte-identical outputs.
//
// Usage:
//   node gen-tokens.mjs --brand vektor
//   node gen-tokens.mjs --brand vektor --out <dir>   # e.g. engine fallback dir
// ─────────────────────────────────────────────────────────────────────────────
import fs from 'node:fs';
import path from 'node:path';
import {resolveBrand, parseBrandArg} from '../lib/brand.mjs';

const argVal = (name) => {
  const i = process.argv.indexOf(name);
  return i >= 0 && i + 1 < process.argv.length ? process.argv[i + 1] : null;
};

const brand = resolveBrand(parseBrandArg(process.argv.slice(2)));
const outDir = argVal('--out') || path.join(brand.brandRoot, 'src', 'generated');

const canonPath = path.join(brand.brandRoot, 'canon', 'americana-tokens.json');
const pendingPath = path.join(brand.brandRoot, 'canon', 'tokens-pending.json');
const canon = JSON.parse(fs.readFileSync(canonPath, 'utf8'));
const pending = JSON.parse(fs.readFileSync(pendingPath, 'utf8'));

const BANNER =
  'GENERATED by reel-engine/scripts/gen-tokens.mjs — NEVER hand-edit; regenerate with `npm run canon:tokens`.';

// ── assemble the field map (canon bg + pending text colors) ──────────────────
// Order follows tokens-pending.json fieldText key order (the locked scene order).
const fields = {};
for (const [name, txt] of Object.entries(pending.fieldText)) {
  const canonBg = canon.color.fields[name];
  const bg = typeof canonBg === 'string' ? canonBg : txt.bg;
  if (typeof bg !== 'string') {
    throw new Error(`field "${name}": no solid bg in canon or tokens-pending.json`);
  }
  if (typeof canonBg === 'string' && txt.bg && txt.bg !== canonBg) {
    throw new Error(`field "${name}": pending bg ${txt.bg} contradicts canon ${canonBg}`);
  }
  for (const k of ['fg', 'muted', 'hairline']) {
    if (typeof txt[k] !== 'string') throw new Error(`field "${name}": missing ${k}`);
  }
  fields[name] = {bg, fg: txt.fg, muted: txt.muted, hairline: txt.hairline};
}

// ── accents straight from canon ──────────────────────────────────────────────
const accents = {};
for (const [name, v] of Object.entries(canon.color.accents ?? {})) {
  if (typeof v === 'string') accents[name] = v;
}

// ── gradient fields from canon (composed to a CSS gradient string) ───────────
const gradients = {};
for (const [name, v] of Object.entries(canon.color.fields ?? {})) {
  if (v && typeof v === 'object' && v.type === 'linear-gradient') {
    gradients[name] = `linear-gradient(${v.angle},${v.stops.join(',')})`;
  }
}

// ── css :root vars from pending (engine style.css defaults, source order) ────
const cssVars = pending.cssRoot ?? {};

// ── extra named colors + font stacks from pending (step-4 migration ledger) ──
const colors = pending.colors ?? {};
const fonts = pending.fonts ?? {};

// canon-derived :root custom properties (--am-*) for style.css consumption.
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const amVars = {};
for (const [name, f] of Object.entries(fields)) amVars[`--am-${kebab(name)}`] = f.bg;
for (const [name, v] of Object.entries(accents)) amVars[`--am-${kebab(name)}`] = v;

// ── emitters ─────────────────────────────────────────────────────────────────
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const tokensTs = [
  `// ${BANNER}`,
  `// Sources: canon/americana-tokens.json + canon/tokens-pending.json (brand: ${brand.name}).`,
  '',
  '// Flat field colors per beat — the Americana Cut skin (=== Video.tsx AM_FIELDS).',
  'export const FIELDS = {',
  ...Object.entries(fields).map(
    ([name, f]) =>
      `  ${name}: {bg: ${q(f.bg)}, fg: ${q(f.fg)}, muted: ${q(f.muted)}, hairline: ${q(f.hairline)}},`,
  ),
  '} as const;',
  '',
  'export type FieldTokens = {bg: string; fg: string; muted: string; hairline: string};',
  '',
  '// Accent colors from canon color.accents.',
  'export const ACCENTS = {',
  ...Object.entries(accents).map(([name, v]) => `  ${name}: ${q(v)},`),
  '} as const;',
  '',
  '// Engine :root CSS custom-property defaults (=== src/style.css :root).',
  'export const CSS_VARS = {',
  ...Object.entries(cssVars).map(([name, v]) => `  ${q(name)}: ${q(v)},`),
  '} as const;',
  '',
  '// Gradient fields from canon color.fields (composed CSS gradient strings).',
  'export const GRADIENTS = {',
  ...Object.entries(gradients).map(([name, v]) => `  ${name}: ${q(v)},`),
  '} as const;',
  '',
  '// Extra named colors pending canonization (canon/tokens-pending.json colors).',
  'export const COLORS = {',
  ...Object.entries(colors).map(([name, v]) => `  ${name}: ${q(v)},`),
  '} as const;',
  '',
  '// Font stacks / font var references (canon/tokens-pending.json fonts).',
  'export const FONTS = {',
  ...Object.entries(fonts).map(([name, v]) => `  ${name}: ${q(v)},`),
  '} as const;',
  '',
].join('\n');

const tokensCss = [
  `/* ${BANNER} */`,
  ':root {',
  ...Object.entries(cssVars).map(([name, v]) => `  ${name}: ${v};`),
  '',
  '  /* canon-derived field/accent colors (americana-tokens.json) */',
  ...Object.entries(amVars).map(([name, v]) => `  ${name}: ${v};`),
  '}',
  '',
].join('\n');

const union = (names) => (names.length ? names.map((n) => `  | ${q(n)}`).join('\n') : '  | never');
const tokenNamesTs = [
  `// ${BANNER}`,
  '',
  'export type FieldName =',
  union(Object.keys(fields)) + ';',
  '',
  'export type AccentName =',
  union(Object.keys(accents)) + ';',
  '',
  'export type CssVarName =',
  union(Object.keys(cssVars)) + ';',
  '',
  'export type GradientName =',
  union(Object.keys(gradients)) + ';',
  '',
  'export type ColorName =',
  union(Object.keys(colors)) + ';',
  '',
  'export type FontName =',
  union(Object.keys(fonts)) + ';',
  '',
  `export const FIELD_NAMES = [${Object.keys(fields).map(q).join(', ')}] as const;`,
  `export const ACCENT_NAMES = [${Object.keys(accents).map(q).join(', ')}] as const;`,
  '',
].join('\n');

const tokenNamesJson =
  JSON.stringify(
    {
      $comment: BANNER,
      fields: Object.keys(fields),
      accents: Object.keys(accents),
      cssVars: Object.keys(cssVars),
      gradients: Object.keys(gradients),
      colors: Object.keys(colors),
      fonts: Object.keys(fonts),
    },
    null,
    2,
  ) + '\n';

// ── write (idempotent) ───────────────────────────────────────────────────────
fs.mkdirSync(outDir, {recursive: true});
const outputs = {
  'tokens.ts': tokensTs,
  'tokens.css': tokensCss,
  'token-names.ts': tokenNamesTs,
  'token-names.json': tokenNamesJson,
};
for (const [file, content] of Object.entries(outputs)) {
  const p = path.join(outDir, file);
  const prev = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
  if (prev !== content) fs.writeFileSync(p, content);
  console.log(`${prev === content ? 'unchanged' : 'wrote    '} ${p}`);
}
