// GENERATED by vektor/scripts/gen-no035-words.mjs — DO NOT HAND-EDIT.
// Source of truth: vektor/data/2026-08-17-mcp-not-apis-kt/captions.json
// (whisper over vo-master.wav, the take that ships).
// Every `ms` is the frame the word is actually spoken on. Re-run the generator
// after any VO or caption change; edit the BEATS spec in the generator, never here.
//
// The generator refuses to emit if any transcript word is unshown or shown twice,
// or if the beats are not contiguous.
import {INK, CREAM, RED, W} from './KTHook';



export type No035Row = {size: number; words: W[]};
export type No035Beat = {from: number; to: number; bg: string; type: string; top?: boolean; rows: No035Row[]};

export const NO035_END_MS = 65360;

export const NO035_BEATS: No035Beat[] = [
  { // hook
    from: 140, to: 7290, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Everyone ", ms: 140, out: 3340},
        {t: "thinks ", ms: 730, out: 3340},
        {t: "MCP ", ms: 1270, out: 3340},
        {t: "replaces ", ms: 1540, out: 3340},
        {t: "your ", ms: 2270, out: 3340},
        {t: "API. ", ms: 2690, out: 3340},
      ]},
      {size: 86, words: [
        {t: "It ", ms: 3340, out: 4220},
        {t: "does ", ms: 3360, out: 4220},
        {t: "not. ", ms: 3630, out: 4220},
      ]},
      {size: 55, words: [
        {t: "What ", ms: 4220, out: 7290},
        {t: "it ", ms: 4350, out: 7290},
        {t: "deletes ", ms: 4490, out: 7290},
        {t: "is ", ms: 4870, out: 7290},
        {t: "the ", ms: 5040, out: 7290},
      ]},
      {size: 134, words: [
        {t: "50 ", ms: 5160, out: 7290, color: RED},
      ]},
      {size: 55, words: [
        {t: "pieces ", ms: 5520, out: 7290},
        {t: "of ", ms: 5840, out: 7290},
        {t: "glue ", ms: 6000, out: 7290},
        {t: "around ", ms: 6320, out: 7290},
        {t: "it. ", ms: 6710, out: 7290},
      ]},
    ]},
  { // mechanism
    from: 7290, to: 18160, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Here ", ms: 7290, out: 10620},
        {t: "is ", ms: 7350, out: 10620},
        {t: "what ", ms: 7420, out: 10620},
        {t: "actually ", ms: 7680, out: 10620},
        {t: "happens. ", ms: 8200, out: 10620},
      ]},
      {size: 86, words: [
        {t: "The ", ms: 8990, out: 12070},
        {t: "model ", ms: 9050, out: 12070},
        {t: "never ", ms: 9330, out: 12070},
        {t: "makes ", ms: 9610, out: 12070},
        {t: "the ", ms: 9900, out: 12070},
        {t: "call. ", ms: 10060, out: 12070},
      ]},
      {size: 55, words: [
        {t: "It ", ms: 10620, out: 14410},
        {t: "decides ", ms: 10640, out: 14410},
        {t: "which ", ms: 11120, out: 14410},
        {t: "tool ", ms: 11360, out: 14410},
        {t: "to ", ms: 11620, out: 14410},
        {t: "run, ", ms: 11770, out: 14410},
      ]},
      {size: 55, words: [
        {t: "your ", ms: 12070, out: 15980},
        {t: "application ", ms: 12330, out: 15980},
        {t: "routes ", ms: 13050, out: 15980},
        {t: "that ", ms: 13440, out: 15980},
        {t: "to ", ms: 13700, out: 15980},
        {t: "a ", ms: 13830, out: 15980},
        {t: "server, ", ms: 13890, out: 15980},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 14410, out: 18160},
        {t: "the ", ms: 14600, out: 18160},
        {t: "server ", ms: 14790, out: 18160},
        {t: "calls ", ms: 15180, out: 18160},
        {t: "Slack ", ms: 15510, out: 18160},
      ]},
      {size: 55, words: [
        {t: "exactly ", ms: 15980, out: 18160},
        {t: "the ", ms: 16400, out: 18160},
        {t: "way ", ms: 16480, out: 18160},
        {t: "your ", ms: 16700, out: 18160},
        {t: "code ", ms: 17020, out: 18160},
        {t: "always ", ms: 17280, out: 18160},
        {t: "did. ", ms: 17720, out: 18160},
      ]},
    ]},
  { // arithmetic
    from: 18160, to: 31480, bg: RED, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "So ", ms: 18160, out: 20910},
        {t: "the ", ms: 18450, out: 20910},
        {t: "thing ", ms: 18540, out: 20910},
        {t: "that ", ms: 18880, out: 20910},
        {t: "goes ", ms: 19170, out: 20910},
        {t: "is ", ms: 19460, out: 20910},
        {t: "not ", ms: 19600, out: 20910},
        {t: "the ", ms: 19820, out: 20910},
        {t: "API, ", ms: 20040, out: 20910},
      ]},
      {size: 86, words: [
        {t: "it ", ms: 20400, out: 22240},
        {t: "is ", ms: 20530, out: 22240},
        {t: "the ", ms: 20810, out: 22240},
        {t: "multiplication. ", ms: 20910, out: 22240},
      ]},
      {size: 55, words: [
        {t: "Five ", ms: 22240, out: 26800},
        {t: "apps ", ms: 22490, out: 26800},
        {t: "talking ", ms: 22740, out: 26800},
        {t: "to ", ms: 23190, out: 26800},
        {t: "10 ", ms: 23310, out: 26800},
        {t: "services ", ms: 23690, out: 26800},
        {t: "is ", ms: 24200, out: 26800},
        {t: "50 ", ms: 24320, out: 26800},
        {t: "integrations ", ms: 24700, out: 26800},
      ]},
      {size: 55, words: [
        {t: "you ", ms: 25470, out: 26800},
        {t: "write ", ms: 25660, out: 26800},
        {t: "by ", ms: 26050, out: 26800},
        {t: "hand. ", ms: 26100, out: 26800},
      ]},
      {size: 55, words: [
        {t: "One ", ms: 26800, out: 29530},
        {t: "server ", ms: 26880, out: 29530},
        {t: "per ", ms: 27360, out: 29530},
        {t: "service, ", ms: 27600, out: 29530},
        {t: "one ", ms: 28400, out: 29530},
        {t: "client ", ms: 28460, out: 29530},
        {t: "per ", ms: 28910, out: 29530},
        {t: "app, ", ms: 29130, out: 29530},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 29530, out: 31480},
        {t: "the ", ms: 29720, out: 31480},
        {t: "same ", ms: 29950, out: 31480},
        {t: "job ", ms: 30240, out: 31480},
        {t: "is ", ms: 30450, out: 31480},
      ]},
      {size: 134, words: [
        {t: "15. ", ms: 30610, out: 31480},
      ]},
    ]},
  { // deprecation
    from: 31480, to: 45440, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 55, words: [
        {t: "If ", ms: 31480, out: 33540},
        {t: "you ", ms: 31540, out: 33540},
        {t: "want ", ms: 31670, out: 33540},
        {t: "proof ", ms: 31920, out: 33540},
        {t: "the ", ms: 32240, out: 33540},
        {t: "protocol ", ms: 32440, out: 33540},
        {t: "agrees, ", ms: 32960, out: 33540},
      ]},
      {size: 55, words: [
        {t: "look ", ms: 33540, out: 35130},
        {t: "at ", ms: 33600, out: 35130},
        {t: "what ", ms: 33680, out: 35130},
        {t: "it ", ms: 33920, out: 35130},
        {t: "just ", ms: 34050, out: 35130},
        {t: "removed. ", ms: 34310, out: 35130},
      ]},
      {size: 55, words: [
        {t: "Sampling ", ms: 35130, out: 37380},
        {t: "was ", ms: 35540, out: 37380},
        {t: "the ", ms: 35650, out: 37380},
        {t: "one ", ms: 35840, out: 37380},
        {t: "feature ", ms: 36030, out: 37380},
        {t: "that ", ms: 36480, out: 37380},
        {t: "let ", ms: 36740, out: 37380},
        {t: "a ", ms: 36930, out: 37380},
        {t: "server ", ms: 36990, out: 37380},
      ]},
      {size: 55, words: [
        {t: "borrow ", ms: 37380, out: 40150},
        {t: "your ", ms: 37770, out: 40150},
        {t: "model ", ms: 38030, out: 40150},
        {t: "without ", ms: 38380, out: 40150},
        {t: "touching ", ms: 38880, out: 40150},
        {t: "a ", ms: 39280, out: 40150},
        {t: "provider. ", ms: 39350, out: 40150},
      ]},
      {size: 55, words: [
        {t: "The ", ms: 40150, out: 41900},
        {t: "July ", ms: 40330, out: 41900},
        {t: "spec ", ms: 40610, out: 41900},
        {t: "deprecates ", ms: 40890, out: 41900},
        {t: "it, ", ms: 41620, out: 41900},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 41900, out: 43690},
        {t: "the ", ms: 42080, out: 43690},
        {t: "advice ", ms: 42290, out: 43690},
        {t: "underneath ", ms: 42710, out: 43690},
        {t: "says ", ms: 43410, out: 43690},
      ]},
      {size: 86, words: [
        {t: "to ", ms: 43690, out: 45440},
        {t: "call ", ms: 43830, out: 45440},
        {t: "the ", ms: 44110, out: 45440},
        {t: "API ", ms: 44320, out: 45440},
        {t: "directly. ", ms: 44560, out: 45440},
      ]},
    ]},
  { // socket
    from: 45440, to: 51680, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "That ", ms: 45440, out: 46980},
        {t: "is ", ms: 45740, out: 46980},
        {t: "the ", ms: 45870, out: 46980},
        {t: "whole ", ms: 46110, out: 46980},
        {t: "idea. ", ms: 46470, out: 46980},
      ]},
      {size: 86, words: [
        {t: "MCP ", ms: 46980, out: 49440},
        {t: "is ", ms: 47180, out: 49440},
        {t: "not ", ms: 47320, out: 49440},
        {t: "a ", ms: 47540, out: 49440},
        {t: "replacement ", ms: 47610, out: 49440},
        {t: "for ", ms: 48420, out: 49440},
        {t: "your ", ms: 48660, out: 49440},
        {t: "API. ", ms: 48930, out: 49440},
      ]},
      {size: 86, words: [
        {t: "It ", ms: 49440, out: 51680},
        {t: "is ", ms: 49600, out: 51680},
        {t: "a ", ms: 49740, out: 51680},
        {t: "standard ", ms: 49840, out: 51680},
        {t: "socket ", ms: 50310, out: 51680},
        {t: "in ", ms: 50660, out: 51680},
        {t: "front ", ms: 50820, out: 51680},
        {t: "of ", ms: 51120, out: 51680},
        {t: "it. ", ms: 51200, out: 51680},
      ]},
    ]},
  { // repo
    from: 51680, to: 58700, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 55, words: [
        {t: "The ", ms: 51680, out: 55370},
        {t: "reference ", ms: 51910, out: 55370},
        {t: "servers ", ms: 52420, out: 55370},
        {t: "are ", ms: 52860, out: 55370},
        {t: "on ", ms: 53040, out: 55370},
        {t: "GitHub ", ms: 53160, out: 55370},
        {t: "at ", ms: 53530, out: 55370},
        {t: "89,000 ", ms: 53690, out: 55370},
        {t: "stars. ", ms: 54700, out: 55370},
      ]},
      {size: 55, words: [
        {t: "Every ", ms: 55370, out: 58700},
        {t: "one ", ms: 55560, out: 58700},
        {t: "of ", ms: 55730, out: 58700},
        {t: "them ", ms: 55840, out: 58700},
        {t: "sits ", ms: 56070, out: 58700},
        {t: "in ", ms: 56340, out: 58700},
        {t: "front ", ms: 56410, out: 58700},
        {t: "of ", ms: 56640, out: 58700},
        {t: "something ", ms: 56790, out: 58700},
        {t: "that ", ms: 57140, out: 58700},
        {t: "already ", ms: 57470, out: 58700},
        {t: "worked. ", ms: 57970, out: 58700},
      ]},
    ]},
  { // outro
    from: 58700, to: 65360, bg: RED, type: CREAM, top: false,
    rows: [
      {size: 55, words: [
        {t: "Send ", ms: 58700, out: 62560},
        {t: "this ", ms: 58970, out: 62560},
        {t: "to ", ms: 59280, out: 62560},
        {t: "whoever ", ms: 59430, out: 62560},
        {t: "keeps ", ms: 59970, out: 62560},
        {t: "telling ", ms: 60350, out: 62560},
        {t: "you ", ms: 60890, out: 62560},
        {t: "MCP ", ms: 61120, out: 62560},
        {t: "replaces ", ms: 61340, out: 62560},
        {t: "rest. ", ms: 61960, out: 62560, caps: true},
      ]},
      {size: 44, words: [
        {t: "Comment ", ms: 62560},
      ]},
      {size: 134, words: [
        {t: "MCP ", ms: 63160, underline: 135, furnMs: 63400, furnColor: CREAM},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 63320},
        {t: "I ", ms: 63620},
        {t: "will ", ms: 63620},
        {t: "send ", ms: 63990},
        {t: "you ", ms: 64240},
        {t: "the ", ms: 64470},
        {t: "diagram. ", ms: 64700},
      ]},
    ]},
];
