// GENERATED by vektor/scripts/gen-no036-words.mjs — DO NOT HAND-EDIT.
// Source of truth: vektor/data/2026-08-18-graphify-kt/captions.json
// (whisper over vo-master.wav, the founder-approved take that ships).
// Every `ms` is the frame the word is actually spoken on. Re-run the generator
// after any VO or caption change; edit the BEATS spec in the generator, never here.
//
// The generator refuses to emit if any transcript word is unshown or shown twice,
// or if the beats are not contiguous.
import {INK, CREAM, RED, W} from './KTHook';



export type No036Row = {size: number; words: W[]};
export type No036Beat = {from: number; to: number; bg: string; type: string; top?: boolean; rows: No036Row[]};

export const NO036_END_MS = 68400;

export const NO036_BEATS: No036Beat[] = [
  { // hook
    from: 120, to: 13360, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "If ", ms: 120, out: 3920},
        {t: "you ", ms: 160, out: 3920},
        {t: "think ", ms: 310, out: 3920},
        {t: "Claude ", ms: 660, out: 3920},
        {t: "Code ", ms: 990, out: 3920},
        {t: "actually ", ms: 1400, out: 3920},
        {t: "knows ", ms: 1770, out: 3920},
        {t: "your ", ms: 2090, out: 3920},
        {t: "codebase, ", ms: 2340, out: 3920},
      ]},
      {size: 86, words: [
        {t: "it ", ms: 3040, out: 7200},
        {t: "is ", ms: 3130, out: 7200},
        {t: "pretending. ", ms: 3260, out: 7200},
      ]},
      {size: 55, words: [
        {t: "Every ", ms: 3920, out: 9520},
        {t: "new ", ms: 4230, out: 9520},
        {t: "session, ", ms: 4410, out: 9520},
        {t: "it ", ms: 4970, out: 9520},
        {t: "rebuilds ", ms: 5120, out: 9520},
        {t: "its ", ms: 5590, out: 9520},
        {t: "mental ", ms: 5770, out: 9520},
        {t: "model ", ms: 6140, out: 9520},
        {t: "from ", ms: 6450, out: 9520},
        {t: "scratch. ", ms: 6700, out: 9520},
      ]},
      {size: 55, words: [
        {t: "The ", ms: 7200, out: 12430},
        {t: "same ", ms: 7390, out: 12430},
        {t: "greps, ", ms: 7640, out: 12430},
        {t: "the ", ms: 8160, out: 12430},
        {t: "same ", ms: 8410, out: 12430},
        {t: "file ", ms: 8820, out: 12430},
        {t: "reads. ", ms: 9090, out: 12430},
      ]},
      {size: 55, words: [
        {t: "Thousands ", ms: 9520, out: 13360},
        {t: "of ", ms: 10060, out: 13360},
        {t: "tokens ", ms: 10180, out: 13360},
        {t: "spent ", ms: 10540, out: 13360},
        {t: "remembering ", ms: 10880, out: 13360},
        {t: "what ", ms: 11520, out: 13360},
        {t: "it ", ms: 11830, out: 13360},
        {t: "already ", ms: 11970, out: 13360},
        {t: "knew ", ms: 12430, out: 13360},
        {t: "yesterday. ", ms: 12710, out: 13360},
      ]},
    ]},
  { // reveal
    from: 13360, to: 30320, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 86, words: [
        {t: "Graphify ", ms: 13360, out: 16560},
        {t: "fixes ", ms: 13930, out: 16560},
        {t: "that. ", ms: 14300, out: 16560},
      ]},
      {size: 55, words: [
        {t: "It ", ms: 14800, out: 16560},
        {t: "is ", ms: 14970, out: 16560},
        {t: "free, ", ms: 15140, out: 16560},
        {t: "open ", ms: 15820, out: 16560},
        {t: "source, ", ms: 16020, out: 16560},
      ]},
      {size: 55, words: [
        {t: "107,000 ", ms: 16560, out: 22000},
        {t: "stars ", ms: 17880, out: 22000},
        {t: "on ", ms: 18210, out: 22000},
        {t: "GitHub. ", ms: 18340, out: 22000},
      ]},
      {size: 55, words: [
        {t: "It ", ms: 18960, out: 25760},
        {t: "scans ", ms: 19080, out: 25760},
        {t: "your ", ms: 19380, out: 25760},
        {t: "codebase ", ms: 19620, out: 25760},
        {t: "once ", ms: 20100, out: 25760},
        {t: "and ", ms: 20340, out: 25760},
        {t: "builds ", ms: 20540, out: 25760},
        {t: "a ", ms: 20900, out: 25760},
        {t: "knowledge ", ms: 20940, out: 25760},
        {t: "graph. ", ms: 21470, out: 25760},
      ]},
      {size: 55, words: [
        {t: "Every ", ms: 22000, out: 28450},
        {t: "function, ", ms: 22320, out: 28450},
        {t: "every ", ms: 23090, out: 28450},
        {t: "connection, ", ms: 23280, out: 28450},
        {t: "every ", ms: 24150, out: 28450},
        {t: "architectural ", ms: 24360, out: 28450},
        {t: "decision. ", ms: 25120, out: 28450},
      ]},
      {size: 55, words: [
        {t: "In ", ms: 25760, out: 30320},
        {t: "one ", ms: 25810, out: 30320},
        {t: "file ", ms: 26010, out: 30320},
        {t: "that ", ms: 26320, out: 30320},
        {t: "every ", ms: 26550, out: 30320},
        {t: "future ", ms: 26910, out: 30320},
        {t: "session ", ms: 27300, out: 30320},
        {t: "can ", ms: 27780, out: 30320},
        {t: "query, ", ms: 27980, out: 30320},
      ]},
      {size: 55, words: [
        {t: "instead ", ms: 28450, out: 30320},
        {t: "of ", ms: 28930, out: 30320},
        {t: "rereading ", ms: 29060, out: 30320},
        {t: "your ", ms: 29670, out: 30320},
        {t: "code. ", ms: 29940, out: 30320},
      ]},
    ]},
  { // run
    from: 30320, to: 40000, bg: RED, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "We ", ms: 30320, out: 32080},
        {t: "ran ", ms: 30510, out: 32080},
        {t: "it ", ms: 30600, out: 32080},
        {t: "on ", ms: 30710, out: 32080},
        {t: "our ", ms: 30820, out: 32080},
        {t: "own ", ms: 30990, out: 32080},
        {t: "render ", ms: 31160, out: 32080},
        {t: "engine. ", ms: 31510, out: 32080},
      ]},
      {size: 55, words: [
        {t: "196 ", ms: 32080, out: 36320},
        {t: "files ", ms: 32870, out: 36320},
        {t: "became ", ms: 33300, out: 36320},
        {t: "a ", ms: 33890, out: 36320},
        {t: "graph ", ms: 33920, out: 36320},
        {t: "of ", ms: 34360, out: 36320},
        {t: "1,700 ", ms: 34530, out: 36320},
        {t: "nodes. ", ms: 35580, out: 36320},
      ]},
      {size: 55, words: [
        {t: "Then ", ms: 36320, out: 38160},
        {t: "we ", ms: 36550, out: 38160},
        {t: "asked ", ms: 36660, out: 38160},
        {t: "it ", ms: 36950, out: 38160},
        {t: "how ", ms: 37060, out: 38160},
        {t: "our ", ms: 37300, out: 38160},
        {t: "caption ", ms: 37400, out: 38160},
      ]},
      {size: 55, words: [
        {t: "system ", ms: 37810, out: 40000},
        {t: "connects ", ms: 38160, out: 40000},
        {t: "to ", ms: 38630, out: 40000},
        {t: "the ", ms: 38800, out: 40000},
        {t: "render ", ms: 38910, out: 40000},
        {t: "pipeline. ", ms: 39260, out: 40000},
      ]},
    ]},
  { // receipt
    from: 40000, to: 50560, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Answering ", ms: 40000, out: 42800},
        {t: "that ", ms: 40620, out: 42800},
        {t: "by ", ms: 40910, out: 42800},
        {t: "reading ", ms: 41050, out: 42800},
        {t: "the ", ms: 41540, out: 42800},
        {t: "files ", ms: 41750, out: 42800},
      ]},
      {size: 55, words: [
        {t: "costs ", ms: 42100, out: 44640},
        {t: "about ", ms: 42450, out: 44640},
        {t: "27,000 ", ms: 42800, out: 44640},
        {t: "tokens. ", ms: 43990, out: 44640},
      ]},
      {size: 55, words: [
        {t: "The ", ms: 44640, out: 46960},
        {t: "graph ", ms: 44830, out: 46960},
        {t: "answered ", ms: 45230, out: 46960},
        {t: "it ", ms: 45690, out: 46960},
        {t: "in ", ms: 45930, out: 46960},
        {t: "2,000. ", ms: 45950, out: 46960},
      ]},
      {size: 86, words: [
        {t: "14 ", ms: 46960, out: 50560, color: RED},
        {t: "times ", ms: 47490, out: 50560, color: RED},
        {t: "less ", ms: 47940, out: 50560, color: RED},
      ]},
      {size: 55, words: [
        {t: "measured ", ms: 48300, out: 50560},
        {t: "on ", ms: 49100, out: 50560},
        {t: "one ", ms: 49190, out: 50560},
        {t: "real ", ms: 49460, out: 50560},
        {t: "question. ", ms: 49820, out: 50560},
      ]},
    ]},
  { // honesty
    from: 50560, to: 61760, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 55, words: [
        {t: "And ", ms: 50560, out: 52880},
        {t: "here ", ms: 50760, out: 52880},
        {t: "is ", ms: 50960, out: 52880},
        {t: "the ", ms: 51070, out: 52880},
        {t: "part ", ms: 51270, out: 52880},
        {t: "the ", ms: 51470, out: 52880},
        {t: "viral ", ms: 51640, out: 52880},
        {t: "versions ", ms: 51930, out: 52880},
        {t: "skip. ", ms: 52400, out: 52880},
      ]},
      {size: 86, words: [
        {t: "They ", ms: 52880, out: 56000},
        {t: "claim ", ms: 53320, out: 56000},
        {t: "70x. ", ms: 53870, out: 56000},
      ]},
      {size: 55, words: [
        {t: "The ", ms: 54640, out: 56000},
        {t: "repo ", ms: 54830, out: 56000},
        {t: "never ", ms: 55040, out: 56000},
        {t: "says ", ms: 55330, out: 56000},
        {t: "that. ", ms: 55560, out: 56000},
      ]},
      {size: 55, words: [
        {t: "It ", ms: 56000, out: 57840},
        {t: "is ", ms: 56150, out: 57840},
        {t: "one ", ms: 56300, out: 57840},
        {t: "user's ", ms: 56530, out: 57840},
        {t: "anecdote. ", ms: 56980, out: 57840},
      ]},
      {size: 55, words: [
        {t: "14x ", ms: 57840, out: 59490},
        {t: "on ", ms: 58370, out: 59490},
        {t: "a ", ms: 58520, out: 59490},
        {t: "real ", ms: 58680, out: 59490},
        {t: "codebase ", ms: 58890, out: 59490},
      ]},
      {size: 55, words: [
        {t: "was ", ms: 59490, out: 61760},
        {t: "enough ", ms: 59720, out: 61760},
        {t: "to ", ms: 60180, out: 61760},
        {t: "keep ", ms: 60330, out: 61760},
        {t: "it ", ms: 60630, out: 61760},
        {t: "installed. ", ms: 60780, out: 61760},
      ]},
    ]},
  { // outro
    from: 61760, to: 68400, bg: RED, type: CREAM, top: false,
    rows: [
      {size: 55, words: [
        {t: "It ", ms: 61760, out: 63520},
        {t: "is ", ms: 61940, out: 63520},
        {t: "two ", ms: 62040, out: 63520},
        {t: "commands ", ms: 62250, out: 63520},
        {t: "to ", ms: 62810, out: 63520},
        {t: "set ", ms: 62950, out: 63520},
        {t: "up. ", ms: 63180, out: 63520},
      ]},
      {size: 44, words: [
        {t: "Comment ", ms: 63520},
      ]},
      {size: 134, words: [
        {t: "graph ", ms: 63960, caps: true, underline: 136, furnMs: 64800, furnColor: CREAM},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 64270},
        {t: "I ", ms: 64510},
        {t: "will ", ms: 64550},
        {t: "send ", ms: 64760},
        {t: "you ", ms: 65010},
        {t: "the ", ms: 65190},
        {t: "repo ", ms: 65370},
        {t: "link ", ms: 65620},
        {t: "and ", ms: 65920},
        {t: "the ", ms: 66130},
        {t: "exact ", ms: 66340},
        {t: "setup ", ms: 66700},
        {t: "we ", ms: 67120},
        {t: "ran. ", ms: 67200},
      ]},
    ]},
];
