// GENERATED by vektor/scripts/gen-tokens-words.mjs — DO NOT HAND-EDIT.
// Source of truth: vektor/data/2026-08-14-token-claims-kt/captions.json (whisper small.en, hand-corrected).
// Every `ms` is the frame the word is actually spoken on. Re-run the generator
// after any VO or caption change; edit the BEATS spec in the generator, never here.
import {INK, CREAM, RED, W} from './KTHook';

export type TokensRow = {size: number; words: W[]};
export type TokensBeat = {from: number; to: number; bg: string; type: string; top?: boolean; rows: TokensRow[]};

export const TOKENS_BEATS: TokensBeat[] = [
  { // hook
    from: 90, to: 7040, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Someone ", ms: 90, out: 1280},
        {t: "gave ", ms: 430, out: 1280},
        {t: "Claude ", ms: 720, out: 1280},
        {t: "Code ", ms: 1060, out: 1280},
      ]},
      {size: 55, words: [
        {t: "semantic ", ms: 1280, out: 3630},
        {t: "search ", ms: 1810, out: 3630},
        {t: "over ", ms: 2160, out: 3630},
        {t: "your ", ms: 2370, out: 3630},
        {t: "whole ", ms: 2540, out: 3630},
        {t: "codebase, ", ms: 2800, out: 3630},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 3630, out: 5900},
        {t: "it ", ms: 3680, out: 5900},
        {t: "cuts ", ms: 3780, out: 5900},
        {t: "your ", ms: 4000, out: 5900},
        {t: "token ", ms: 4160, out: 5900},
        {t: "usage ", ms: 4560, out: 5900},
        {t: "by ", ms: 5120, out: 5900},
        {t: "about ", ms: 5340, out: 5900},
      ]},
      {size: 134, words: [
        {t: "forty ", ms: 5900},
        {t: "percent. ", ms: 6338, ring: 3401, furnMs: 6598, furnColor: RED, color: RED},
      ]},
    ],
  },
  { // why
    from: 7040, to: 18680, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Here ", ms: 7040, out: 8450},
        {t: "is ", ms: 7320, out: 8450},
        {t: "why ", ms: 7410, out: 8450},
        {t: "that ", ms: 7600, out: 8450},
        {t: "works. ", ms: 7840, out: 8450},
      ]},
      {size: 44, words: [
        {t: "Grep ", ms: 8450, out: 9760},
        {t: "reads ", ms: 8610, out: 9760},
        {t: "your ", ms: 8880, out: 9760},
        {t: "whole ", ms: 9120, out: 9760},
        {t: "repo ", ms: 9470, out: 9760},
      ]},
      {size: 55, words: [
        {t: "looking ", ms: 9760, out: 10800},
        {t: "for ", ms: 10090, out: 10800},
        {t: "a ", ms: 10240, out: 10800},
        {t: "match, ", ms: 10320, out: 10800},
      ]},
      {size: 44, words: [
        {t: "so ", ms: 10800, out: 11970},
        {t: "everything ", ms: 10920, out: 11970},
        {t: "it ", ms: 11470, out: 11970},
        {t: "touches ", ms: 11630, out: 11970},
      ]},
      {size: 44, words: [
        {t: "goes ", ms: 11970, out: 13660},
        {t: "into ", ms: 12190, out: 13660},
        {t: "the ", ms: 12410, out: 13660},
        {t: "context ", ms: 12580, out: 13660},
        {t: "window. ", ms: 12960, out: 13660},
      ]},
      {size: 44, words: [
        {t: "Semantic ", ms: 13660, out: 15120},
        {t: "search ", ms: 14050, out: 15120},
        {t: "reads ", ms: 14450, out: 15120},
        {t: "only ", ms: 14800, out: 15120},
      ]},
      {size: 44, words: [
        {t: "the ", ms: 15120, out: 16730},
        {t: "part ", ms: 15330, out: 16730},
        {t: "that ", ms: 15440, out: 16730},
        {t: "actually ", ms: 15680, out: 16730},
        {t: "matters, ", ms: 16190, out: 16730},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 16730},
        {t: "hands ", ms: 16820},
        {t: "the ", ms: 17170},
        {t: "model ", ms: 17330},
        {t: "that ", ms: 17650},
        {t: "instead. ", ms: 17900},
      ]},
    ],
  },
  { // proof
    from: 18680, to: 23770, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 44, words: [
        {t: "The ", ms: 18680, out: 19920},
        {t: "reason ", ms: 18740, out: 19920},
        {t: "I ", ms: 19110, out: 19920},
        {t: "trust ", ms: 19180, out: 19920},
        {t: "this ", ms: 19470, out: 19920},
        {t: "one ", ms: 19710, out: 19920},
      ]},
      {size: 55, words: [
        {t: "is ", ms: 19920, out: 20160},
        {t: "that ", ms: 20030, out: 20160},
      ]},
      {size: 55, words: [
        {t: "they ", ms: 20160, out: 21740},
        {t: "published ", ms: 20320, out: 21740},
        {t: "the ", ms: 20720, out: 21740},
        {t: "benchmark. ", ms: 20940, out: 21740, underline: 3403, furnMs: 21200, furnColor: RED, color: RED},
      ]},
      {size: 44, words: [
        {t: "Nobody ", ms: 21740},
        {t: "else ", ms: 22150},
        {t: "in ", ms: 22420},
        {t: "this ", ms: 22550},
        {t: "category ", ms: 22820},
        {t: "did. ", ms: 23540},
      ]},
    ],
  },
  { // experiment
    from: 23770, to: 31840, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 44, words: [
        {t: "They ", ms: 23770, out: 25530},
        {t: "took ", ms: 24040, out: 25530},
        {t: "thirty ", ms: 24310, out: 25530, ring: 3405, furnMs: 24570, furnColor: RED, color: RED},
        {t: "real ", ms: 24720, out: 25530},
        {t: "bug ", ms: 24990, out: 25530},
        {t: "fixes ", ms: 25190, out: 25530},
      ]},
      {size: 69, words: [
        {t: "from ", ms: 25530, out: 26810},
        {t: "SWE-bench. ", ms: 25800, out: 26810},
      ]},
      {size: 55, words: [
        {t: "Each ", ms: 26810, out: 28740},
        {t: "method ", ms: 27060, out: 28740},
        {t: "ran ", ms: 27500, out: 28740},
        {t: "three ", ms: 27740, out: 28740},
        {t: "times, ", ms: 28120, out: 28740},
      ]},
      {size: 69, words: [
        {t: "six ", ms: 28740, out: 30050},
        {t: "runs ", ms: 28970, out: 30050},
        {t: "in ", ms: 29280, out: 30050},
        {t: "total, ", ms: 29420, out: 30050},
      ]},
      {size: 44, words: [
        {t: "same ", ms: 30050},
        {t: "model ", ms: 30360},
        {t: "on ", ms: 30750},
        {t: "both ", ms: 30910},
        {t: "sides. ", ms: 31210},
      ]},
    ],
  },
  { // numbers
    from: 31840, to: 41640, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 44, words: [
        {t: "Seventy-three ", ms: 31840, out: 33920},
        {t: "thousand ", ms: 32434, out: 33920},
        {t: "tokens ", ms: 32800, out: 33920},
        {t: "per ", ms: 33270, out: 33920},
        {t: "fix ", ms: 33520, out: 33920},
      ]},
      {size: 44, words: [
        {t: "came ", ms: 33920, out: 35950},
        {t: "down ", ms: 34170, out: 35950},
        {t: "to ", ms: 34410, out: 35950},
        {t: "forty-four ", ms: 34540, out: 35950},
        {t: "thousand. ", ms: 35282, out: 35950},
      ]},
      {size: 44, words: [
        {t: "Eight ", ms: 35950, out: 37560},
        {t: "tool ", ms: 36210, out: 37560},
        {t: "calls ", ms: 36370, out: 37560},
        {t: "came ", ms: 36690, out: 37560},
        {t: "down ", ms: 36940, out: 37560},
        {t: "to ", ms: 37190, out: 37560},
        {t: "five. ", ms: 37320, out: 37560},
      ]},
      {size: 44, words: [
        {t: "And ", ms: 37560, out: 38760},
        {t: "the ", ms: 37740, out: 38760},
        {t: "answer ", ms: 38000, out: 38760},
        {t: "quality ", ms: 38320, out: 38760},
      ]},
      {size: 55, words: [
        {t: "came ", ms: 38760, out: 39760},
        {t: "out ", ms: 39120, out: 39760},
        {t: "the ", ms: 39280, out: 39760},
        {t: "same, ", ms: 39440, out: 39760},
      ]},
      {size: 55, words: [
        {t: "which ", ms: 39760},
        {t: "is ", ms: 40080},
        {t: "the ", ms: 40240},
        {t: "part ", ms: 40400},
        {t: "that ", ms: 40650},
        {t: "matters. ", ms: 40920},
      ]},
    ],
  },
  { // cost
    from: 41640, to: 52870, bg: RED, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Best ", ms: 41640, out: 42380},
        {t: "of ", ms: 41820, out: 42380},
        {t: "all, ", ms: 41950, out: 42380},
      ]},
      {size: 55, words: [
        {t: "you ", ms: 42380, out: 44240},
        {t: "install ", ms: 42460, out: 44240},
        {t: "it ", ms: 42910, out: 44240},
        {t: "in ", ms: 43040, out: 44240},
        {t: "one ", ms: 43170, out: 44240},
        {t: "command. ", ms: 43360, out: 44240},
      ]},
      {size: 69, words: [
        {t: "It ", ms: 44240, out: 45200},
        {t: "is ", ms: 44260, out: 45200},
        {t: "not ", ms: 44400, out: 45200},
        {t: "free ", ms: 44780, out: 45200},
        {t: "though. ", ms: 44880, out: 45200},
      ]},
      {size: 44, words: [
        {t: "It ", ms: 45200, out: 46380},
        {t: "wants ", ms: 45390, out: 46380},
        {t: "an ", ms: 45660, out: 46380},
        {t: "OpenAI ", ms: 45790, out: 46380},
        {t: "key ", ms: 46180, out: 46380},
      ]},
      {size: 55, words: [
        {t: "for ", ms: 46380, out: 47430},
        {t: "the ", ms: 46580, out: 47430},
        {t: "embeddings ", ms: 46780, out: 47430},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 47430, out: 48552},
        {t: "a ", ms: 47630, out: 48552},
        {t: "Zilliz ", ms: 47690, out: 48552},
        {t: "account ", ms: 48088, out: 48552},
      ]},
      {size: 55, words: [
        {t: "for ", ms: 48552, out: 49760},
        {t: "the ", ms: 48750, out: 49760},
        {t: "vector ", ms: 48940, out: 49760},
        {t: "store, ", ms: 49340, out: 49760},
      ]},
      {size: 44, words: [
        {t: "so ", ms: 49760, out: 51060},
        {t: "you ", ms: 49900, out: 51060},
        {t: "are ", ms: 50040, out: 51060},
        {t: "spending ", ms: 50210, out: 51060},
        {t: "someone ", ms: 50670, out: 51060},
      ]},
      {size: 55, words: [
        {t: "else's ", ms: 51060},
        {t: "tokens ", ms: 51410},
        {t: "to ", ms: 51740},
        {t: "save ", ms: 51860},
        {t: "your ", ms: 52090},
        {t: "own. ", ms: 52320},
      ]},
    ],
  },
  { // find
    from: 52870, to: 56070, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 44, words: [
        {t: "Just ", ms: 52870, out: 55010},
        {t: "search ", ms: 52970, out: 55010},
        {t: "Claude ", ms: 53380, out: 55010},
        {t: "Context ", ms: 53750, out: 55010},
        {t: "on ", ms: 54250, out: 55010},
        {t: "GitHub. ", ms: 54320, out: 55010},
      ]},
      {size: 69, words: [
        {t: "It ", ms: 55010},
        {t: "is ", ms: 55050},
        {t: "MIT ", ms: 55140},
        {t: "licensed. ", ms: 55340},
      ]},
    ],
  },
  { // cta
    from: 56070, to: 64540, bg: RED, type: CREAM, top: false,
    rows: [
      {size: 44, words: [
        {t: "Send ", ms: 56070, out: 57230},
        {t: "this ", ms: 56620, out: 57230},
        {t: "to ", ms: 56700, out: 57230},
        {t: "whoever ", ms: 56750, out: 57230},
      ]},
      {size: 55, words: [
        {t: "keeps ", ms: 57230, out: 58320},
        {t: "telling ", ms: 57580, out: 58320},
        {t: "you ", ms: 58050, out: 58320},
      ]},
      {size: 44, words: [
        {t: "the ", ms: 58320, out: 60240},
        {t: "context ", ms: 58530, out: 60240},
        {t: "window ", ms: 58960, out: 60240},
        {t: "is ", ms: 59280, out: 60240},
        {t: "the ", ms: 59360, out: 60240},
        {t: "problem. ", ms: 59610, out: 60240},
      ]},
      {size: 55, words: [
        {t: "Comment ", ms: 60240},
      ]},
      {size: 134, words: [
        {t: "CONTEXT ", ms: 60660, underline: 3407, furnMs: 60920, furnColor: CREAM},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 61080},
        {t: "I ", ms: 61250},
        {t: "will ", ms: 61320},
        {t: "send ", ms: 61560},
        {t: "you ", ms: 61800},
        {t: "the ", ms: 61980},
        {t: "install ", ms: 62160},
        {t: "line ", ms: 62580},
        {t: "and ", ms: 62820},
        {t: "the ", ms: 63000},
        {t: "evaluation. ", ms: 63180},
      ]},
    ],
  },
];

export const TOKENS_END_MS = 64540;
