// GENERATED by vektor/scripts/gen-tokens-words.mjs — DO NOT HAND-EDIT.
// Source of truth: vektor/data/2026-08-14-token-claims-kt/captions.json (whisper small.en, hand-corrected).
// Every `ms` is the frame the word is actually spoken on. Re-run the generator
// after any VO or caption change; edit the BEATS spec in the generator, never here.
import {INK, CREAM, RED, W} from './KTHook';

export type TokensRow = {size: number; words: W[]};
export type TokensBeat = {from: number; to: number; bg: string; type: string; top?: boolean; rows: TokensRow[]};

export const TOKENS_BEATS: TokensBeat[] = [
  { // hook
    from: 120, to: 5840, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Someone ", ms: 120, out: 3420},
        {t: "gave ", ms: 430, out: 3420},
        {t: "Claude ", ms: 710, out: 3420},
        {t: "Code ", ms: 1040, out: 3420},
      ]},
      {size: 55, words: [
        {t: "semantic ", ms: 1280, out: 3420},
        {t: "search ", ms: 1770, out: 3420},
        {t: "over ", ms: 2180, out: 3420},
        {t: "your ", ms: 2320, out: 3420},
        {t: "whole ", ms: 2480, out: 3420},
        {t: "codebase ", ms: 2700, out: 3420},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 3420},
        {t: "it ", ms: 3440},
        {t: "cuts ", ms: 3520},
        {t: "your ", ms: 3760},
        {t: "token ", ms: 3840},
        {t: "usage ", ms: 4240},
        {t: "by ", ms: 4550},
      ]},
      {size: 134, words: [
        {t: "40%. ", ms: 4800, ring: 3401, furnMs: 5060, furnColor: RED, color: RED},
      ]},
    ],
  },
  { // proof
    from: 5840, to: 9920, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "It's ", ms: 5840, out: 8370},
        {t: "so ", ms: 6060, out: 8370},
        {t: "good ", ms: 6170, out: 8370},
        {t: "they ", ms: 6410, out: 8370},
        {t: "put ", ms: 6700, out: 8370},
      ]},
      {size: 69, words: [
        {t: "the ", ms: 6830, out: 8370},
        {t: "benchmark ", ms: 6970, out: 8370, underline: 3403, furnMs: 7230, furnColor: RED, color: RED},
        {t: "in ", ms: 7520, out: 8370},
        {t: "the ", ms: 7600, out: 8370},
        {t: "repo. ", ms: 7770, out: 8370},
      ]},
      {size: 55, words: [
        {t: "Nobody ", ms: 8370},
        {t: "else ", ms: 8520},
        {t: "in ", ms: 8700},
        {t: "this ", ms: 8790},
        {t: "category ", ms: 8970},
      ]},
      {size: 86, words: [
        {t: "did ", ms: 9350},
        {t: "that. ", ms: 9520},
      ]},
    ],
  },
  { // experiment
    from: 9920, to: 20080, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 44, words: [
        {t: "So ", ms: 9920, out: 14750},
        {t: "as ", ms: 10160, out: 14750},
        {t: "you ", ms: 10230, out: 14750},
        {t: "can ", ms: 10440, out: 14750},
        {t: "see, ", ms: 10660, out: 14750},
        {t: "you ", ms: 11080, out: 14750},
        {t: "get ", ms: 11250, out: 14750},
      ]},
      {size: 55, words: [
        {t: "30 ", ms: 11470, out: 14750, ring: 3405, furnMs: 11730, furnColor: RED, color: RED},
        {t: "real ", ms: 11920, out: 14750},
        {t: "bug ", ms: 12220, out: 14750},
        {t: "fixes ", ms: 12440, out: 14750},
        {t: "from ", ms: 12810, out: 14750},
        {t: "SWE-bench ", ms: 13110, out: 14750},
      ]},
      {size: 86, words: [
        {t: "run ", ms: 13760, out: 14750},
        {t: "twice. ", ms: 14060, out: 14750},
      ]},
      {size: 55, words: [
        {t: "Once ", ms: 14750, out: 16330},
        {t: "with ", ms: 14800, out: 16330},
        {t: "grep, ", ms: 14980, out: 16330},
      ]},
      {size: 55, words: [
        {t: "once ", ms: 15540, out: 16330},
        {t: "with ", ms: 15680, out: 16330},
        {t: "search. ", ms: 15840, out: 16330},
      ]},
      {size: 55, words: [
        {t: "You ", ms: 16330, out: 18340},
        {t: "get ", ms: 16650, out: 18340},
        {t: "the ", ms: 16740, out: 18340},
        {t: "same ", ms: 16810, out: 18340},
        {t: "answer ", ms: 17030, out: 18340},
        {t: "quality ", ms: 17350, out: 18340},
      ]},
      {size: 69, words: [
        {t: "either ", ms: 17740, out: 18340},
        {t: "way, ", ms: 18080, out: 18340},
      ]},
      {size: 44, words: [
        {t: "which ", ms: 18340},
        {t: "is ", ms: 18720},
        {t: "the ", ms: 18740},
        {t: "part ", ms: 18880},
        {t: "that ", ms: 19100},
        {t: "matters. ", ms: 19320},
      ]},
    ],
  },
  { // numbers
    from: 20080, to: 24540, bg: INK, type: CREAM, top: true,
    rows: [
      {size: 44, words: [
        {t: "You ", ms: 20080, out: 22630},
        {t: "get ", ms: 20130, out: 22630},
      ]},
      {size: 55, words: [
        {t: "73,373 ", ms: 20240, out: 22630},
        {t: "tokens ", ms: 21280, out: 22630},
        {t: "down ", ms: 21720, out: 22630},
        {t: "to ", ms: 22010, out: 22630},
        {t: "44,449 ", ms: 22150, out: 22630, ring: 3411, furnMs: 22410, furnColor: RED, color: RED},
      ]},
      {size: 55, words: [
        {t: "and ", ms: 22630},
        {t: "8 ", ms: 22810},
        {t: "tool ", ms: 23070},
        {t: "calls ", ms: 23320},
        {t: "down ", ms: 23680},
        {t: "to ", ms: 23970},
        {t: "5. ", ms: 24110},
      ]},
    ],
  },
  { // cost
    from: 24540, to: 36060, bg: RED, type: CREAM, top: true,
    rows: [
      {size: 55, words: [
        {t: "Best ", ms: 24540, out: 27710},
        {t: "of ", ms: 24830, out: 27710},
        {t: "all, ", ms: 24960, out: 27710},
        {t: "you ", ms: 25340, out: 27710},
        {t: "can ", ms: 25550, out: 27710},
        {t: "install ", ms: 25770, out: 27710},
        {t: "it ", ms: 26320, out: 27710},
      ]},
      {size: 86, words: [
        {t: "in ", ms: 26420, out: 27710},
        {t: "one ", ms: 26560, out: 27710},
        {t: "command. ", ms: 26780, out: 27710},
      ]},
      {size: 69, words: [
        {t: "It's ", ms: 27710, out: 29240},
        {t: "not ", ms: 27820, out: 29240},
        {t: "totally ", ms: 27990, out: 29240},
        {t: "free ", ms: 28400, out: 29240, strike: 3413, furnMs: 28660, furnColor: CREAM},
        {t: "though. ", ms: 28630, out: 29240},
      ]},
      {size: 44, words: [
        {t: "It ", ms: 29240, out: 33260},
        {t: "wants ", ms: 29260, out: 33260},
        {t: "an ", ms: 29560, out: 33260},
        {t: "OpenAI ", ms: 29660, out: 33260},
        {t: "key ", ms: 30000, out: 33260},
        {t: "for ", ms: 30170, out: 33260},
        {t: "the ", ms: 30370, out: 33260},
        {t: "embeddings ", ms: 30510, out: 33260},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 31190, out: 33260},
        {t: "a ", ms: 31370, out: 33260},
        {t: "Zilliz ", ms: 31420, out: 33260},
        {t: "account ", ms: 31840, out: 33260},
        {t: "for ", ms: 32160, out: 33260},
        {t: "the ", ms: 32240, out: 33260},
        {t: "vector ", ms: 32400, out: 33260},
        {t: "store. ", ms: 32730, out: 33260},
      ]},
      {size: 44, words: [
        {t: "So ", ms: 33260},
        {t: "you're ", ms: 33270},
        {t: "spending ", ms: 33590},
        {t: "someone ", ms: 34030},
        {t: "else's ", ms: 34410},
        {t: "tokens ", ms: 34770},
      ]},
      {size: 55, words: [
        {t: "to ", ms: 35070},
        {t: "save ", ms: 35180},
        {t: "your ", ms: 35400},
        {t: "own. ", ms: 35620},
      ]},
    ],
  },
  { // find
    from: 36060, to: 41760, bg: CREAM, type: INK, top: true,
    rows: [
      {size: 44, words: [
        {t: "Just ", ms: 36060, out: 37970},
        {t: "search ", ms: 36170, out: 37970},
      ]},
      {size: 107, words: [
        {t: "Claude ", ms: 36560, out: 37970},
        {t: "Context ", ms: 36920, out: 37970},
      ]},
      {size: 55, words: [
        {t: "on ", ms: 37350, out: 37970},
        {t: "GitHub. ", ms: 37460, out: 37970},
      ]},
      {size: 44, words: [
        {t: "Send ", ms: 37970},
        {t: "this ", ms: 38420},
        {t: "to ", ms: 38480},
        {t: "whoever ", ms: 38600},
        {t: "keeps ", ms: 39020},
        {t: "telling ", ms: 39320},
        {t: "you ", ms: 39740},
      ]},
      {size: 55, words: [
        {t: "the ", ms: 39920},
        {t: "context ", ms: 40120},
        {t: "window ", ms: 40520},
        {t: "is ", ms: 40880},
        {t: "the ", ms: 40990},
        {t: "problem. ", ms: 41200},
      ]},
    ],
  },
  { // cta
    from: 41760, to: 48300, bg: RED, type: CREAM, top: false,
    rows: [
      {size: 44, words: [
        {t: "I ", ms: 41760, out: 44640},
        {t: "check ", ms: 41950, out: 44640},
        {t: "this ", ms: 42110, out: 44640},
        {t: "stuff ", ms: 42350, out: 44640},
        {t: "every ", ms: 42640, out: 44640},
        {t: "week, ", ms: 42920, out: 44640},
      ]},
      {size: 44, words: [
        {t: "so ", ms: 43280, out: 44640},
        {t: "follow ", ms: 43400, out: 44640},
        {t: "to ", ms: 43750, out: 44640},
        {t: "catch ", ms: 43870, out: 44640},
        {t: "the ", ms: 44160, out: 44640},
        {t: "rest. ", ms: 44350, out: 44640},
      ]},
      {size: 55, words: [
        {t: "Comment ", ms: 44640},
      ]},
      {size: 134, words: [
        {t: "CONTEXT ", ms: 44990, underline: 3421, furnMs: 45250, furnColor: CREAM},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 45330, out: 46740},
        {t: "I'll ", ms: 45490, out: 46740},
        {t: "send ", ms: 45720, out: 46740},
        {t: "you ", ms: 45890, out: 46740},
        {t: "the ", ms: 46040, out: 46740},
        {t: "install ", ms: 46190, out: 46740},
        {t: "line ", ms: 46540, out: 46740},
      ]},
      {size: 44, words: [
        {t: "and ", ms: 46740},
        {t: "the ", ms: 46890},
        {t: "evaluation. ", ms: 47040},
      ]},
    ],
  },
];

export const TOKENS_END_MS = 48300;
